import { Router } from "express";
import { requireAuth } from "../middleware/auth";
import { me, publicProfile, updateProfile, inbox, markOpened, toggleFavorite, deleteMessage } from "../controllers/userController";
const router = Router();
router.get("/me", requireAuth, me);
router.get("/public/:username", publicProfile);
router.patch("/profile", requireAuth, updateProfile);
router.get("/messages", requireAuth, inbox);
router.patch("/messages/:id/open", requireAuth, markOpened);
router.patch("/messages/:id/favorite", requireAuth, toggleFavorite);
router.delete("/messages/:id", requireAuth, deleteMessage);
export default router;
